apiVersion: k3d.io/v1alpha5
kind: Simple

metadata:
  name: cilium-cni-ingress

servers: 1
agents: 2

image: docker.io/rancher/k3s:v1.31.5-k3s1

network: cilium-cni-ingress-network

ports:
  - port: 8082:80
    nodeFilters:
      - loadbalancer

options:
  k3s:
    extraArgs:
      - arg: "--disable=traefik"
        nodeFilters:
          - server:*
      - arg: "--disable=servicelb"
        nodeFilters:
          - server:*
      - arg: "--flannel-backend=none"
        nodeFilters:
          - server:*
      - arg: "--disable-network-policy"
        nodeFilters:
          - server:*

  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: false
