apiVersion: k3d.io/v1alpha5
kind: Simple

metadata:
  name: otel-operator

servers: 1
agents: 3

image: docker.io/rancher/k3s:v1.31.5-k3s1
network: otel-operator-network

ports:
  - port: 4005:80
    nodeFilters:
      - loadbalancer

files:
  # Otel operator files
  - description: "otel namespace"
    source: ./otel-operator/otel-operator-namespace.yaml
    destination: /var/lib/rancher/k3s/server/manifests/otel-operator-namespace.yaml
  - description: "otel-operator installation manifest"
    source: ./otel-operator/otel-operator-install.yaml
    destination: /var/lib/rancher/k3s/server/manifests/otel-operator-install.yaml
  - description: "otel collector deployment"
    source: ./otel-operator/otel-operator-collector-deployment.yaml
    destination: /var/lib/rancher/k3s/server/manifests/collector-deployment.yaml
  - description: "otel collector daemonset"
    source: ./otel-operator/otel-operator-collector-daemonset.yaml
    destination: /var/lib/rancher/k3s/server/manifests/collector-daemonset.yaml
  - description: "otel collector daemonset ServiceAccount"
    source: ./otel-operator/otel-operator-collector-daemonset-sa.yaml
    destination: /var/lib/rancher/k3s/server/manifests/collector-daemonset-sa.yaml
  - description: "otel collector deployment ServiceAccount"
    source: ./otel-operator/otel-operator-collector-deployment-sa.yaml
    destination: /var/lib/rancher/k3s/server/manifests/collector-deployment-sa.yaml
    # kube-prometheus-stack files
  - description: "kps namespace"
    source: ./kube-prometheus-stack/kps-namespace.yaml
    destination: /var/lib/rancher/k3s/server/manifests/kps-namespace.yaml
  - description: "kps installation manifest"
    source: ./kube-prometheus-stack/kps-install.yaml
    destination: /var/lib/rancher/k3s/server/manifests/kps-install.yaml

registries:
  config: ../registries.yaml

options:
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: false
