apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor-tls
  namespace: harbor
spec:
  secretName: harbor-tls
  dnsNames:
    - localhost
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
