#!/bin/bash

/usr/local/bin/mise trust /workspaces/$DEVPOD_WORKSPACE_ID/mise.toml && /usr/local/bin/mise install

/usr/local/bin/mise exec helm -- helm repo add harbor https://helm.goharbor.io
/usr/local/bin/mise exec helm -- helm repo add open-telemetry https://open-telemetry.github.io/opentelemetry-helm-charts
/usr/local/bin/mise exec helm -- helm repo update
